name       : spice
version    : 0.14.3
release    : 12
source     :
    - https://www.spice-space.org/download/releases/spice-server/spice-0.14.3.tar.bz2 : 551d4be4a07667cf0543f3c895beb6da8a93ef5a9829f2ae47817be5e616a114
license    : BSD-3-Clause
summary    : Spice Server
description: |
    Spice Server
component  : desktop.library
optimize   : speed
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libcacard)
    - pkgconfig(libsasl2)
    - pkgconfig(liblz4)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(spice-protocol)
    - lz4-devel
    - libjpeg-turbo-devel
setup      : |
    %reconfigure --disable-static \
               --disable-celt051 \
               --enable-lz4 \
               --enable-opengl
build      : |
    %make
install    : |
    %make_install
