name       : spice
version    : 0.14.1
release    : 9
source     :
    - https://www.spice-space.org/download/releases/spice-server/spice-0.14.1.tar.bz2 : 1ead5de63d06eededed4017db37240f07bef0abffbaf621899647e7e685a1519
license    : BSD-3-Clause
summary    : Spice Server
description: |
    Spice Server
component  : desktop.library
optimize   : speed
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libcacard)
    - pkgconfig(libsasl2)
    - pkgconfig(liblz4)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(spice-protocol)
    - lz4-devel
    - libjpeg-turbo-devel
setup      : |
    %reconfigure --disable-static \
               --disable-celt051 \
               --enable-lz4 \
               --enable-opengl
build      : |
    %make
install    : |
    %make_install
