name       : spice
version    : 0.15.2
release    : 19
source     :
    - https://www.spice-space.org/download/releases/spice-server/spice-0.15.2.tar.bz2 : 6d9eb6117f03917471c4bc10004abecff48a79fb85eb85a1c45f023377015b81
homepage   : https://www.spice-space.org
license    : BSD-3-Clause
summary    : SPICE (Simple Protocol for Independent Computing Environments)
description: |
    SPICE (Simple Protocol for Independent Computing Environments) is a remote display system built for virtual environments which allows you to view a computing 'desktop' environment not only on the machine where it is running, but from anywhere on the Internet and from a wide variety of machine architectures.
component  : desktop.library
optimize   : speed
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libcacard)
    - pkgconfig(libsasl2)
    - pkgconfig(liblz4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(spice-protocol)
    - glib-networking # check
setup      : |
    sed -i "/add_dist_script/d" meson.build

    %meson_configure -Dgstreamer=no
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
