name       : spice
version    : 0.12.8
release    : 5
source     :
    - git|https://anongit.freedesktop.org/git/spice/spice.git : a957a90baf2c62d31f3547e56bba7d0e812d2331
license    : BSD-3-Clause
summary    : Spice Server
description: |
    Spice Server
component  : desktop.library
optimize   : speed
builddeps  :
    - pkgconfig(spice-protocol)
    - pkgconfig(pixman-1)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libcacard)
    - pkgconfig(libsasl2)
    - pkgconfig(liblz4)
    - lz4-devel
    - libjpeg-turbo-devel
setup      : |
    %reconfigure --disable-static \
               --disable-celt051 \
               --enable-lz4 \
               --enable-opengl
build      : |
    %make
install    : |
    %make_install
