name       : spice
version    : 0.12.6
release    : 1
source     :
    - http://www.spice-space.org/download/releases/spice-0.12.6.tar.bz2 : f148ea30135bf80a4f465ce723a1cd6d4ccb34c098b6298a020b378ace8569b6
license    : BSD-3-Clause
summary    : Spice Server
description: |
    Spice Server
builddeps  :
    - pkgconfig(spice-protocol)
    - pkgconfig(pixman-1)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(liblz4)
    - lz4-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static \
               --disable-celt051 \
               --enable-lz4 \
               --enable-opengl
build      : |
    %make
install    : |
    %make_install
